#!/usr/bin/env bash

workspace_pressed=$1
current_active_workspace=$(hyprctl activeworkspace | awk '/workspace ID/ {print $3}')
if [[ ! -f /tmp/previous_workspace ]]; then
    previous_active_workspace=1
else
    previous_active_workspace=$(cat /tmp/previous_workspace)
fi

# if we hit the same key as the workspace we're on, go to last known workspace
if [[ "$current_active_workspace" == "$workspace_pressed" ]]; then
    hyprctl dispatch workspace "$previous_active_workspace"
else
    hyprctl dispatch workspace "$workspace_pressed"
fi
echo "$current_active_workspace" | tee /tmp/previous_workspace > /dev/null
